language: go

go_import_path: github.com/syberalexis/linky-exporter

sudo: false
jobs:
  include:
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
      script:
        - make clean build
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
        - GOARCH=arm
        - GOARM=5
      script:
        - make clean build
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
        - GOARCH=arm
        - GOARM=6
      script:
        - make clean build
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
        - GOARCH=arm
        - GOARM=7
      script:
        - make clean build
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
        - GOARCH=arm64
      script:
        - make clean build

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true