language: go

go_import_path: github.com/syberalexis/linky-exporter

os: linux
dist: xenial
go: 1.14.x

sudo: false
jobs:
  include:
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=linux
        - GOARCH=amd64
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=linux
        - GOARCH=arm
        - GOARM=5
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=linux
        - GOARCH=arm
        - GOARM=6
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=linux
        - GOARCH=arm
        - GOARM=7
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=linux
        - GOARCH=amd64
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=windows
        - GOARCH=arm
        - GOARM=6
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=windows
        - GOARCH=arm
        - GOARM=7
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=freebsd
        - GOARCH=amd64
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=openbsd
        - GOARCH=amd64
    - stage: build
      env:
        - GO111MODULE=on
        - GOOS=darwin
        - GOARCH=amd64

script: make clean build

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true