{
 "title": "Linky exporter",
 "description": "Dashboard to French electrical system (EDF)",
 "tags": [
  "linky",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "linky_id",
    "label": "LinkyId",
    "query": {
     "query": "label_values(linky_timestamp, linky_id)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_timestamp{linky_id=\"$linky_id\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Contrat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_timestamp{linky_id=\"$linky_id\"}",
     "legendFormat": "{{contract}}"
    }
   ]
  },
  {
   "title": "Index en cours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_timestamp{linky_id=\"$linky_id\"}",
     "legendFormat": "{{pricing}}"
    }
   ]
  },
  {
   "title": "Puissance utilisée totale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_energy_total{linky_id=\"$linky_id\", mode=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation de la Puissance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_power{linky_id=\"$linky_id\", mode=\"used\"}",
     "legendFormat": "Phase {{phase}}"
    },
    {
     "expr": "linky_power_reference{linky_id=\"$linky_id\", type=\"subscribed\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linky_energy{linky_id=\"$linky_id\", mode=\"used\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "options": {
    "content": "Si Contrat Heure Creuse :\n- Index F1 = Index Heures Creuses\n- Index F2 = Index Heures Pleines"
   }
  },
  {
   "title": "Energie instantanée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "idelta(linky_energy{linky_id=\"$linky_id\"}[$interval])",
     "legendFormat": "Index {{index}}"
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "linky_power{linky_id=\"$linky_id\", mode=\"used\"}",
     "legendFormat": "Phase {{phase}}"
    },
    {
     "expr": "linky_power_reference{linky_id=\"$linky_id\", type=\"subscribed\"} * 1000",
     "legendFormat": "Subscribed"
    }
   ]
  },
  {
   "title": "Intensité courante",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "linky_intensity{linky_id=\"$linky_id\"}",
     "legendFormat": "Phase {{phase}}"
    }
   ]
  },
  {
   "title": "Energie consommée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "linky_energy{linky_id=\"$linky_id\", mode=\"used\"}",
     "legendFormat": "Index used {{index}}"
    }
   ]
  }
 ]
}